# Conocimiento del Cliente a través de los Datos 

Autora: Claudia Reina Vargas

## Introducción

El sector turístico, se trata de un sector que, debido a la globalización y la revolución digital del sistema entre otros factores a destacar, se ha vuelto altamente competitivo. Por ello ha surgido la necesidad de formular nuevas estrategias de marketing y análisis de datos para la reinvención del sector en un destino en concreto. La alta competencia y las facilidades que tiene el turista a la hora de poder seleccionar el destino son claves para el crecimiento de este sector. Si hablamos del caso de España, según los datos del Ministerio de Industria Comercio y Turismo, en 2022 se superaron las cifras pre-pandemia por la Covid-19, alcanzando los 71,6 millones de turistas internacionales que realizaron un gasto de 87.061 millones de euros. 
En cuanto al gasto, los datos arrojan un aumento del 10,5% de media por turista frente a 2019 y las estancias aumentaron a una media de 7,5 días de media. Observando estas cifras, podemos ver que el turismo está sufriendo un gran auge, pero ¿hasta cuándo durará esto? El aumento del coste de vida ha sido notable en muchas industrias, y puede, que ciertos modelos de turismo en países estacionalizados no sea viable en un futuro. 
Muchas empresas, en sus inicios, estaban presentes únicamente en un mercado concreto y en una tipología concreta de turismo, pero se vieron obligadas a lanzarse al mercado internacional para poder subsistir al crecimiento de otras entidades extranjeras. Pero el propio consumidor ha cambiado también sus hábitos de compra y consumo de servicios, teniendo mayor poder de decisión y negociación que las propias empresas.  A diario se reciben miles de estímulos que impulsan a tomar unas u otras decisiones de compra. El marketing ha visto enormemente ampliados sus horizontes gracias al aumento del número de canales de comunicación como consecuencia de la digitalización
El uso de big data analytics supone una importante oportunidad para las empresas turísticas que quieran aumentar sus ventas tanto para el público nacional como para el internacional.


### Titular

Vivamus libero leo, accumsan non turpis vel, eleifend sodales mauris. Donec pellentesque, tellus a lacinia vestibulum, nisl lacus dapibus nibh, id tincidunt turpis erat non nisl. Donec ornare imperdiet metus, eu sollicitudin risus elementum non. Aliquam metus eros, maximus dignissim pellentesque nec, venenatis vitae purus. Vivamus laoreet mi magna, ac malesuada tellus condimentum in. Integer nulla lectus, finibus sit amet ex nec, finibus molestie diam. Pellentesque gravida ac erat sit amet tempus.


